fname = input("What is your first name? ")
lname = input("What is your last name? ")
age = input("How old are you? (Number Only) ") 
school = input("How many years have you been in high school? ")
print (fname, lname + " is " + age + " years old and has been in high school for " + school + " years.") 
